### ISSUE TITLE
Trial README run-through fails on some unit tests and on Examples/addr1

### ISSUE THREAD

**Issue by jabowery** [fredyouhanaie/espace#1]
Find the attached [ran_readme.log](https://github.com/fredyouhanaie/espace/files/11907896/ran_readme.log) session log which executed under `/home/jabowery/kerl/25.3.2/bin/erl` and [rebar3 version 3.21.0](https://github.com/erlang/rebar3/releases/download/3.21.0/rebar3) .

**Comment by fredyouhanaie** [comment]
Hi James, thanks for trying the software and reporting the issue.

I had left out a compile step in the README instructions, now fixed :-)

Feel free to close the issue, if happy with the fix.

Cheers,
f.

**Comment by fredyouhanaie** [comment]
I should also clarify that the unit tests in were successful

> Finished in 2.517 seconds
> 91 tests, 0 failures

The stopped/killed log messages are part of the test runs.
